import React from "react";
import Head from "next/head";
import { Navbar } from "../components/basket";
import styles from "../styles/Layout.module.css";

const Layout = ({ children }) => {
  return (
    <>
      <Navbar />
      <main className={styles.main}>
        <Head>
          <title>Estate App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
      </main>
    </>
  );
};

export default Layout;
